[build]
  command = "CI=false npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-local-install-core"

[functions.schedule-fetch-videos]
  cron = "0 0 */5 * *"  # Runs every 5 days
